### ISSUE TITLE
Ansible fails on check: TASK [Ansible-Security-Compliance.rhel7-role-stig-rhel7-disa : set auth pam_faillock before pam_unix.so]

### ISSUE THREAD

**Issue by snypeur** [RedHatOfficial/ansible-rhel7-disa-stig-role#1]
`fatal: [stig-test-lx]: FAILED! => {"changed": false, "module_stderr": "Shared connection to stig-test-lx closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_0tsyFx/ansible_module_pamd.py\", line 785, in <module>\r\n    main()\r\n  File \"/tmp/ansible_0tsyFx/ansible_module_pamd.py\", line 752, in main\r\n    valid, msg = service.validate()\r\n  File \"/tmp/ansible_0tsyFx/ansible_module_pamd.py\", line 656, in validate\r\n    if not current_line.is_valid()[0]:\r\nTypeError: 'bool' object is not callable\r\n", "msg": "MODULE FAILURE", "rc": 1}`

**Comment by Akasurde** [comment]
@snypeur You can check this https://github.com/ansible/ansible/pull/42025 and https://github.com/MindPointGroup/RHEL7-STIG/pull/106

**Comment by Akasurde** [comment]
https://github.com/ansible/ansible/issues/42864

**Comment by redhatrises** [comment]
This is the officially Red Hat supported DISA STIG role repo over MindPointGroup. As these issues appear to be fixed. Closing.
