### ISSUE TITLE
Updates for V2R2?

### ISSUE THREAD

**Issue by medberry** [RedHatOfficial/ansible-rhel7-disa-stig-role#10]
RHEL7 STIG Version 2 Release 2 was published on 2019-01-18. I don't see updates herein reflecting that.

**Comment by redhatrises** [comment]
Tickets are tracked at https://github.com/ComplianceAsCode/content. The reason V2R2 changes have not been made is because of RHEL8 release priority in addition to the fact that some of the V2R2 changes introduce security vulnerabilities that Red Hat didn't agree to.

**Comment by redhatrises** [comment]
Closing as V2R2 tracking is being handled in a different repository.

**Comment by bracketttc** [comment]
> some of the V2R2 changes introduce security vulnerabilities that Red Hat didn't agree to.

Is there any public forum where this is enumerated? I work sometimes on compliance for a system which must comply with the STIG and would not mind pushing back on any requirements that actually work against the stated goal of increasing security.

**Comment by redhatrises** [comment]
@bracketttc https://github.com/ComplianceAsCode/content is probably the best place.
