### ISSUE TITLE
"name" should come first in tasks/ files

### ISSUE THREAD

**Issue by jamescassell** [RedHatOfficial/ansible-rhel7-disa-stig-role#5]
It's not technically required, but it makes it much easier to review the content if each task starts with a "name"

**Comment by redhatrises** [comment]
Good point @jamescassell didn't notice this. Fix has been submitted upstream at https://github.com/ComplianceAsCode/content/pull/3518

**Comment by redhatrises** [comment]
@jamescassell this should be fixed now.

**Comment by jamescassell** [comment]
Awesome, thanks!
