### ISSUE TITLE
set_fact overrides any user customizations

### ISSUE THREAD

**Issue by jamescassell** [RedHatOfficial/ansible-rhel7-disa-stig-role#9]
for example, there's a 'set_fact' that sets `inactivity_timeout_value` even though it's already set in vars/  Doing a set_fact makes it all but impossible to override.  This is worse than #4.

**Comment by redhatrises** [comment]
@jamescassell this should be fixed upsteam by https://github.com/ComplianceAsCode/content/pull/3607
